# ----------------------------------------------------------------------------
#
# Package             : rgba-regex
# Source Repo         : https://github.com/davidtheclark/postcss-resolve-nested-selector
# Travis Job Link     : https://travis-ci.com/github/asellappen/postcss-resolve-nested-selector/
# Created travis.yml  : No
# Maintainer          : Arumugam N S <asellappen@yahoo.com>/Priya Seth<sethp@us.ibm.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------
language: node_js
arch:
  - amd64
  - ppc64le
node_js:
  - 'stable'
  - '14'
